-- ============================================================================
-- 20260809000100_rls_class_rule
--
-- The RLS obligation, expressed as a COMPUTED CLASS RULE rather than a list of
-- table names -- spec §7 preamble, H26-C3.
--
-- Owner: Atlas (schema).  RLS POLICIES themselves are Vault's (`supabase/
-- policies/`, CODEOWNERS:74). This migration writes no policy. It writes the
-- rule that decides which tables need one.
--
-- ---------------------------------------------------------------------------
-- WHY A RULE AND NOT A LIST
--
-- CLAUDE.md constraint 5 and README:335 both say "`voices` is a global
-- catalogue and is exempt" -- an ENUMERATION with exactly one member. Spec §7
-- states the same obligation as a CLASS: "A table is exempt when it carries no
-- user data at all -- not when it happens to be called `voices`." The class
-- grew to two members (`voices`, `voice_langs`) on its first opportunity, and
-- the enumeration in the two governing documents was stale the same day.
--
-- An allowlist is defeatable by ADDITION: append a name and a table leaves the
-- obligation silently. This rule is not a list. Membership is DERIVED from the
-- catalog:
--
--     A table is OBLIGATED to carry RLS iff it can reach user data --
--     i.e. it has a `user_id` column, or it has a foreign key (transitively)
--     to a table that does.
--
-- That is exactly §7's own stated mechanism -- "by `user_id` where the column
-- exists, by join through `documents` otherwise" -- executed instead of
-- described. `voices` has no `user_id` and no outbound FK; `voice_langs` has
-- one FK, to `voices`. Neither reaches user data, so neither is inside the
-- obligation. Adding a catalogue table needs no edit here. Adding a table that
-- touches a user makes this rule fail until RLS is on.
--
-- ---------------------------------------------------------------------------
-- WHERE THE RULE CAN STILL BE DEFEATED, STATED RATHER THAN HIDDEN
--
-- The rule keys on the column NAME `user_id`. A table that stores the user
-- under `owner_id` is invisible to it. That is a real hole and it is not
-- closed by pretending otherwise, so `rls_class_violations()` reports a second
-- kind, `unclassifiable`: a table with no `user_id` and no FK path to one, but
-- carrying a column whose name looks like a user key under another spelling.
-- Such a table is not auto-exempted -- it is FLAGGED for a human decision.
-- Renaming the column therefore moves a table from "obligated" to "needs a
-- ruling", never to "exempt".
--
-- Not covered, and deliberately: a user identifier stored under a name this
-- regex does not anticipate, and RLS enabled with zero policies (which denies
-- everything -- a Vault concern, not an exemption concern).
--
-- ---------------------------------------------------------------------------
-- RECONCILIATION GREP (CLAUDE.md "The reconciliation pass"), run BEFORE editing
--   grep -rn -F "<ident>" CLAUDE.md README.md resources/specs resources/roadmap
--
--   voices                32 files-lines  reconciled -- §7.1 column run is the
--                                         source for 20260809000200
--   voice_langs           32              reconciled -- §7.1a is the source for
--                                         20260809000300
--   assert_rls_class_rule  0              NEW, implementation-only. No document
--   rls_obligated_tables   0              names it and none should: these are
--   rls_class_violations   0              function names, not design facts.
--   set_updated_at         0              Deliberately unreconciled.
--   private (schema)       0              NEW, implementation-only.
--
--   DELIBERATELY UNCHANGED: CLAUDE.md:224 and README.md:335 both name `voices`
--   alone. That is roadmap:689-695 (Owner: Scribe, due 2026-08-15) and it is
--   NOT this migration's to fix -- editing the governing documents was
--   explicitly out of scope this round. Neither line is WRONG about the
--   obligation (neither table carries user data); both are incomplete
--   enumerations, which is precisely the defect this file replaces with a rule.
--
-- ROLLBACK: forward-only (Atlas rule 9). To reverse, write a later migration
-- that drops these functions; do not edit this file once applied.
-- ============================================================================

-- Helpers live OUTSIDE `public` so PostgREST never exposes them as RPC. The
-- schema is not granted to anyone: these are called by migrations and by
-- supabase/tests/verify_voice_langs.mjs, not by clients.
create schema if not exists private;
revoke all on schema private from public;

comment on schema private is
  'Internal schema helpers. Not exposed via PostgREST. No user data.';


-- ---------------------------------------------------------------------------
-- updated_at. A trigger rather than an application convention, because "the
-- application always sets it" is a claim and a trigger is a fact.
-- ---------------------------------------------------------------------------
create or replace function private.set_updated_at()
returns trigger
language plpgsql
as $fn$
begin
  new.updated_at := now();
  return new;
end;
$fn$;

comment on function private.set_updated_at() is
  'BEFORE UPDATE trigger: stamps updated_at. Never touches any measured-at '
  'column -- "when did this row change" and "when was this measured" are two '
  'different facts (spec §7.1a).';


-- ---------------------------------------------------------------------------
-- The class rule.
-- ---------------------------------------------------------------------------
create or replace function private.rls_obligated_tables()
returns table (relid regclass, reason text)
language sql
stable
as $fn$
  with recursive
  tbl as (
    select c.oid as t_oid
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where c.relkind = 'r'
      and n.nspname = 'public'
      and not c.relispartition
  ),
  direct as (
    select distinct t.t_oid
    from tbl t
    join pg_attribute a on a.attrelid = t.t_oid
    where a.attname = 'user_id'
      and a.attnum > 0
      and not a.attisdropped
  ),
  -- UNION (not UNION ALL) on a single oid column: the set dedups, so a cycle
  -- of foreign keys terminates instead of recursing forever.
  reach as (
    select d.t_oid from direct d
    union
    select fk.conrelid
    from reach r
    join pg_constraint fk on fk.confrelid = r.t_oid and fk.contype = 'f'
    where fk.conrelid in (select t_oid from tbl)
  )
  select r.t_oid::regclass,
         case when exists (select 1 from direct d where d.t_oid = r.t_oid)
              then 'carries user data directly: has a user_id column'
              else 'reaches user data through a foreign key chain'
         end
  from reach r;
$fn$;

comment on function private.rls_obligated_tables() is
  'Tables in `public` that are INSIDE the RLS obligation, computed from the '
  'catalog: has user_id, or has a foreign key path to a table that does. '
  'Membership is derived, never listed. Spec §7 preamble.';


create or replace function private.rls_class_violations()
returns table (relid regclass, kind text, reason text)
language sql
stable
as $fn$
  -- (1) Inside the obligation, RLS off. The failure the rule exists to catch.
  select o.relid, 'rls_missing'::text, o.reason
  from private.rls_obligated_tables() o
  join pg_class c on c.oid = o.relid
  where not c.relrowsecurity

  union all

  -- (2) Outside the obligation as computed, but carrying something that looks
  -- like a user key under another name. NOT auto-exempt: flagged for a ruling.
  -- This is what stops the rule being defeated by renaming a column.
  select c.oid::regclass,
         'unclassifiable'::text,
         'no user_id and no foreign-key path to one, but column "' ||
         a.attname || '" looks like a user key under another name -- classify '
         'this table by hand before treating it as a catalogue'
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  join pg_attribute a
    on a.attrelid = c.oid and a.attnum > 0 and not a.attisdropped
  where c.relkind = 'r'
    and n.nspname = 'public'
    and not c.relispartition
    and a.attname ~ '^(owner|account|profile|customer|member|tenant|org|organization|auth|subject|person|holder)_id$'
    and c.oid not in (select o.relid::oid from private.rls_obligated_tables() o);
$fn$;

comment on function private.rls_class_violations() is
  'Empty means the class rule holds. kind=rls_missing: inside the obligation '
  'with RLS off. kind=unclassifiable: the rule cannot see whether this table '
  'carries user data -- a human decides, and the default is NOT exempt.';


create or replace function private.assert_rls_class_rule()
returns void
language plpgsql
stable
as $fn$
declare
  v   record;
  msg text := '';
begin
  for v in select * from private.rls_class_violations() loop
    msg := msg || format(E'\n  %s [%s] %s', v.relid, v.kind, v.reason);
  end loop;
  if msg <> '' then
    raise exception 'RLS class rule violated:%', msg
      using hint =
        'Spec §7: a table is exempt only when it carries NO user data. '
        'Enable RLS and give Vault a policy, or state why the rule cannot see '
        'the user column. Do not add the table to a list -- there is no list.';
  end if;
end;
$fn$;

comment on function private.assert_rls_class_rule() is
  'Raises if any table in `public` violates the RLS class rule. Called at the '
  'end of every table-creating migration, and by '
  'supabase/tests/verify_voice_langs.mjs.';

revoke all on function private.set_updated_at() from public;
revoke all on function private.rls_obligated_tables() from public;
revoke all on function private.rls_class_violations() from public;
revoke all on function private.assert_rls_class_rule() from public;
